/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package findmycareer;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.SwingWorker;

/**
/**
 * @author Robert Strachan
 * @StudentNO: 9105393616
 * @version 0.2
 * @Date 16/06/2017
 * @Bugs none
 */
public class DatabasePopUp extends javax.swing.JFrame {
    private JFrame adminScreen;
    private int num = 0;
    
    
    class ProgressBarUpdate extends SwingWorker<Void, Void>{

        @Override
        protected Void doInBackground(){
            SQLreader.create(dbProgress, txtDbName.getText(), txtDbUser.getText(), txtDbPass.getText());
            return null;  
        }
        
        @Override
        public void done(){
            closeWindow();
        }
        
    }
    
    public void closeWindow(){
        adminScreen.setEnabled(true);
        String oldUser = Settings.getSetting("username");
        String oldPassword = Settings.getSetting("password");
        String server = Settings.getSetting("server");
        String port = Settings.getSetting("port");
        //System.out.println("DATABASE RENAME: " + txtDbName.getText());
        Settings.setSetting("db", txtDbName.getText());
        Settings.setSetting("url_db", "jdbc:mysql://" + server + ":" + port + "/" + txtDbName.getText());
        Settings.setSetting("url", "jdbc:mysql://" + server + ":" + port);
        FMCdb.changeDbuser(oldUser, oldPassword, oldUser);
        

        this.setVisible(false);
        //Message.okPopup("<html><center>Database reset complete!</center><br><br><center> Program must be restared.</center></html>");
        Message.okPopup("<html>Database rebuild complete!</html>");
        adminScreen.setVisible(true);
        this.dispose();  
    }
    /**
     * Creates new form DatabasePopUp
     */
    public DatabasePopUp() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }
    
    public DatabasePopUp(JFrame admin) {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        adminScreen = admin;
        adminScreen.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dbCardStack = new javax.swing.JPanel();
        confirmPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDbResetCancel = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dbResetPanel = new javax.swing.JPanel();
        txtDbUser = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        txtDbPass = new javax.swing.JPasswordField();
        txtDbVerify = new javax.swing.JPasswordField();
        lblPass = new javax.swing.JLabel();
        lblVerify = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        dbProgress = new javax.swing.JProgressBar();
        lblName = new javax.swing.JLabel();
        txtDbName = new javax.swing.JTextField();
        lblWait = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                onClose(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("DATABASE REBUILD");

        dbCardStack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        dbCardStack.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setText("Do you wish to continue?");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setText("<html><b><center>WARNING!</center></b><br>Rebuilding database will clear<br> <center>all data stored within it. </center></html>");

        btnDbResetCancel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnDbResetCancel.setText("Cancel");
        btnDbResetCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbCancelClick(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confimClick(evt);
            }
        });

        javax.swing.GroupLayout confirmPanelLayout = new javax.swing.GroupLayout(confirmPanel);
        confirmPanel.setLayout(confirmPanelLayout);
        confirmPanelLayout.setHorizontalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDbResetCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmPanelLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(57, 57, 57))
            .addGroup(confirmPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        confirmPanelLayout.setVerticalGroup(
            confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmPanelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(86, 86, 86)
                .addGroup(confirmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnDbResetCancel))
                .addContainerGap())
        );

        dbCardStack.add(confirmPanel, "confirmCard");

        txtDbUser.setText("root");

        lblUser.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblUser.setText("Database Root user");

        lblPass.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblPass.setText("Database Password");

        lblVerify.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblVerify.setText("Re-Type Password");

        btnSubmit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitClick(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backClick(evt);
            }
        });

        dbProgress.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dbProgress.setStringPainted(true);

        lblName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblName.setText("Database Name");

        lblWait.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        lblWait.setText("Please wait...");

        javax.swing.GroupLayout dbResetPanelLayout = new javax.swing.GroupLayout(dbResetPanel);
        dbResetPanel.setLayout(dbResetPanelLayout);
        dbResetPanelLayout.setHorizontalGroup(
            dbResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbResetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dbResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dbResetPanelLayout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addContainerGap(333, Short.MAX_VALUE))
                    .addGroup(dbResetPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(dbResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSubmit)
                            .addGroup(dbResetPanelLayout.createSequentialGroup()
                                .addGroup(dbResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblName)
                                    .addComponent(lblUser)
                                    .addComponent(lblPass)
                                    .addComponent(lblVerify))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(dbResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDbName)
                                    .addComponent(txtDbPass)
                                    .addComponent(txtDbUser, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtDbVerify, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(89, 89, 89))
                    .addGroup(dbResetPanelLayout.createSequentialGroup()
                        .addComponent(dbProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(dbResetPanelLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(lblWait)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dbResetPanelLayout.setVerticalGroup(
            dbResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbResetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dbResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtDbName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(dbResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dbResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDbPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dbResetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDbVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVerify))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit)
                .addGap(52, 52, 52)
                .addComponent(lblWait)
                .addGap(100, 100, 100)
                .addComponent(dbProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnBack)
                .addContainerGap())
        );

        dbCardStack.add(dbResetPanel, "resetCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dbCardStack, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(dbCardStack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbCancelClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbCancelClick
        // TODO add your handling code here:
        adminScreen.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_dbCancelClick

    private void confimClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confimClick
        // TODO add your handling code here:
        CardLayout card = (CardLayout) dbCardStack.getLayout();
        txtDbName.setText(Settings.getSetting("db"));
        card.show(dbCardStack, "resetCard");
        dbProgress.setVisible(false);
        lblWait.setVisible(false);
    }//GEN-LAST:event_confimClick

    private void submitClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitClick
        // TODO add your handling code here:
        if(Validate.isValidString(txtDbName) && Validate.isValidUsername(txtDbUser) && Validate.isValidDbPassword(txtDbPass, txtDbVerify)){
            if(Validate.isValidConnection(txtDbUser.getText(), txtDbPass.getText())){
                this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                lblWait.setVisible(true);
                dbProgress.setVisible(true);
                txtDbName.setVisible(false);
                txtDbUser.setVisible(false);
                txtDbPass.setVisible(false);
                txtDbVerify.setVisible(false);
                dbProgress.setMaximum(SQLreader.countCodeLines());
                btnBack.setVisible(false);
                btnSubmit.setVisible(false);
                lblName.setVisible(false);
                lblUser.setVisible(false);
                lblPass.setVisible(false);
                lblVerify.setVisible(false);
                
                ProgressBarUpdate task = new ProgressBarUpdate();
                task.execute();  
                
            }else{
                Message.error("<html><b>Database connection could not be made.</b><br>"
                        + "<br>Current server: " + Settings.getSetting("server")
                        + "<br>Current PORT : " +  Settings.getSetting("port")
                        + "</html>");
            }
        } 
    }//GEN-LAST:event_submitClick
 
    private void backClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backClick
        // TODO add your handling code here:
        CardLayout card = (CardLayout) dbCardStack.getLayout();
        card.show(dbCardStack, "confirmCard");
    }//GEN-LAST:event_backClick

    private void onClose(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onClose
        adminScreen.setEnabled(true);
        adminScreen.setVisible(true);
    }//GEN-LAST:event_onClose

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatabasePopUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDbResetCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JPanel confirmPanel;
    private javax.swing.JPanel dbCardStack;
    private javax.swing.JProgressBar dbProgress;
    private javax.swing.JPanel dbResetPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblVerify;
    private javax.swing.JLabel lblWait;
    private javax.swing.JTextField txtDbName;
    private javax.swing.JPasswordField txtDbPass;
    private javax.swing.JTextField txtDbUser;
    private javax.swing.JPasswordField txtDbVerify;
    // End of variables declaration//GEN-END:variables
}
