/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package findmycareer;

import java.util.ArrayList;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author 4109013411
 */
public class LoginJFrame extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;

    /**
     * Creates new form LoginJFrame
     */
    public LoginJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        btnNew = new javax.swing.JButton();
        txtusername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FMC");

        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpassword.setText("jPasswordField1");

        btnNew.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNew.setText("new");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        txtusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtusername.setText("username id");

        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogin.setText("login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(txtpassword)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNew))
            .addComponent(txtusername)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnLogin)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        Registration RegistrationObject=new Registration(this);
        RegistrationObject.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
//        //all commentd out 4 now//jes simple valid 4 simple admin n password
//        try{ 
//            String username=jTextField1.getText(); 
//        char[] pwd=jPasswordField1.getPassword(); 
//        String password=new String(pwd);
//        //new wt dave told me 2 do
//        ArrayList client = FMCdb.getClients();
//        System.out.println(client.size());
//        for(int i=0;i<client.size();i++){
//            System.out.println(client);
//        }
//        //end of//new wt dave told me 2 do
//        if(username.equals("admin")&&password.equals("password")){ 
//            JOptionPane.showMessageDialog(null,"Valid User"); 
//        } else JOptionPane.showMessageDialog(null,"Invalid User"); 
//        } catch(Exception e){ 
//            System.out.println(e.getMessage());
//        }
//        //end of //jes simple valid 4 simple admin n password
        
        String user = txtusername.getText();
        String pass = txtpassword.getText();
        boolean userFound=false;        


        
        if(Validate.isValidUsername(txtusername)){
            ArrayList<Client> clientList = FMCdb.getClients();
        for(int i = 0; i<clientList.size(); i++){
            if(clientList.get(i).getUsername().equals(user) && clientList.get(i).getPassword().equals(pass)){
                System.out.println("Client found");
                new SearchForCareer(this, clientList.get(i)).setVisible(true);
                userFound = true;
                break;
            }
        }
        ArrayList<Consultant> consultantList = FMCdb.getConsultants();
        for(int i = 0; i<consultantList.size(); i++){
            if(consultantList.get(i).getUsername().equals(user) && consultantList.get(i).getPassword().equals(pass)){
                System.out.println("Consultant found");
                new ConsultantUI(this).setVisible(true);
                userFound = true;
                break;
            }
        }
        ArrayList<Administrator> adminList = FMCdb.getAdmins();
        for(int i = 0; i<adminList.size(); i++){
            if(adminList.get(i).getUsername().equals(user) && adminList.get(i).getPassword().equals(pass)){
                System.out.println("Admin found");
                
                AdministratorScreen AdministratorScreenObject=new AdministratorScreen(this, adminList.get(i));
                AdministratorScreenObject.setVisible(true);
                userFound = true;
                break;
            }
        }
        }
        if(!userFound) Message.warnPopup("User not found.");
        if(userFound) this.setVisible(false);
        
        
        
//        conn=MysqlConnect.ConnectDB();
//        String Sql="SELECT * FROM `administrator` where username=? and password=?";
//        try{
//            pst=conn.prepareStatement(Sql);
//            pst.setString(1, txtusername.getText());
//            pst.setString(2, txtpassword.getText());
//            rs=pst.executeQuery();
//            if(rs.next()){
//                JOptionPane.showMessageDialog(null, "welcome user");
//                Welcome w=new Welcome();
//                w.setVisible(true);
//                
//            }else{
//                JOptionPane.showMessageDialog(null, "invalid username/password","access denied",JOptionPane.ERROR_MESSAGE);
//                
//            }
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnNew;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
